### ISSUE TITLE
Chore: Change test framework from Mocha to Jest.

### ISSUE THREAD

**Issue by objmj-itminds** [IT-Minds-opensource/ts-array-ext#14]
I personally have come to like Jest a bit more.
Not only can we get a better setup faster with some codecov the required config is also easier to read.

**Comment by arielhad** [comment]
@objmj-itminds Can I try to work on this?

**Comment by objmj-itminds** [comment]
Certainly. 

If you could please include this section in jest config

```javascript
{
 collectCoverage: true,
 coverageReporters: ["lcov"],
 coverageDirectory: "test-coverage",
 coverageThreshold: { 
 global: {
   branches: 80,
   functions: 80,
   lines: 80,
   statements: 80
 }
}
```

Then I will visit and adjust the coverage values another time.

**Comment by arielhad** [comment]
Should I use jest or ts-jest ?

**Comment by objmj-itminds** [comment]
I have personally never used ts-jest but getting to avoid babel seems
promising and it being a heavily used development dependency doesn't alarm
me.

So I say go for it.

Martin Johannesson

Senior Software Developer, IT Minds København

**Comment by arielhad** [comment]
Im getting permission denied error when trying to push my branch  😕

**Comment by objmj-itminds** [comment]
@arielhad Thanks for letting us know - the other PRs we have merged have been via forks. I will look into opening the feature, chore, bugfix branches.

**Comment by arielhad** [comment]
Got it, PR can be found  [HERE](https://github.com/IT-Minds-opensource/ts-array-ext/pull/19)
