### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by arielhad** [IT-Minds-opensource/ts-array-ext#25]
Add an option `Select` functionality where an attribute can be selected to be the comparable field.

Example usage

`ourScores.Select(score => score.points)` will create new array with the selected fields

Thoughts?

**Comment by objmj-itminds** [comment]
How would this differ from using `.map` ?

**Comment by arielhad** [comment]
Good point 😉 
Im searching for a new things that can be added..
