### ISSUE TITLE
Feature request. Give the option for findAndReplace to provide a mutator function in place of the full object.

### ISSUE THREAD

**Issue by objmj-itminds** [IT-Minds-opensource/ts-array-ext#6]
It would be preferable if there was an option to the `findAndReplace` function that took in place of the full object a mutator function.

Idea usage

```typescript

type User = {
  id: string;
  name: string
}

const users: User[] = [...]

users.findAndReplace(x => x.id === "5", x => ({...x, name: "NewName69"})
```

**Comment by objmj-itminds** [comment]
How should we handle the case of the object not being found while `addIfNotFound` is set to true?
This would mean that in the above example x would be undefined and thus throw an error.

**Comment by phillip-itminds** [comment]
@objmj-itminds 
Perhaps they need to be split up into two functions at this point. `findAndReplace` and `findAndReplaceOrCreate` perhaps?
Because that feature doesn't really make sense with the create option.
